- hosts: localhost
  connection: local
  gather_facts: no    # 実行前に対象サーバの情報を収集する
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/dupes
      - caskroom/cask
      - sanemat/font
  tasks:
    - name: homebrewのtapリポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes
